#!/bin/sh
#
# Configuring host communication.
#

case "$1" in
  start)
	modprobe sstf-iosched
	echo sstf > /sys/block/sda/queue/scheduler
	;;
  stop)
	
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
